server:
  port: 8888

spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
#  resources:
#    static-locations: classpath:/static/
  data:
    mongodb:
      host: 172.23.43.28
      port: 27017
      database: label_db
  datasource:
    url: jdbc:mysql://172.23.43.28:3306/db_label_platform?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ncu151568

mybatis:
  #mybatis mapper文件的位置
  mapper-locations: classpath:mapper/*Mapper.xml
  #扫描pojo类的位置,在此处指明扫描实体类的包
  type-aliases-package: com.labeling.demo.entity