server:
  port: 9300
spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
  resources:
    static-locations: classpath:/static/
  datasource:
    url: jdbc:mysql://localhost:3306/db_label_platform?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ncu151568
  servlet:
    multipart:
      max-file-size: 500MB  #限制单个文件大小
      max-request-size: 1000MB #限制总文件大小
      enabled: true
mybatis:
  #mybatis mapper文件的位置
  mapper-locations: classpath:mapper/*Mapper.xml
  #扫描pojo类的位置,在此处指明扫描实体类的包
  type-aliases-package: com.labeling.demo.entity

logging:
  level:
    com.labeling.demo.repository: debug
